Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2021-12, with the labels that each got.

#561 feat(gux-modal): focusTrap prop is now updatable
  src/components/stable/gux-modal/gux-modal.tsx
Labels: simple review

#563 fix(gux-datepicker): fixed datepicker date selection bugs
  src/components/stable/gux-calendar/gux-calendar.tsx
  src/components/stable/gux-calendar/readme.md
  src/components/stable/gux-datepicker/gux-datepicker.tsx
Labels: backport

#574 fix(gux-dropdown-v2): fixed selected item overflow
  src/components/beta/gux-dropdown-v2/example.html
  src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less
  src/components/beta/gux-dropdown-v2/gux-option-v2/gux-option-v2.less
Labels: backport

#572 feat(gux-radial-progress): added scale prop
  src/components/stable/gux-radial-progress/example.html
  src/components/stable/gux-radial-progress/gux-radial-progress.less
  src/components/stable/gux-radial-progress/gux-radial-progress.service.ts
  src/components/stable/gux-radial-progress/gux-radial-progress.tsx
  src/components/stable/gux-radial-progress/gux-radial-progress.types.ts
  src/components/stable/gux-radial-progress/readme.md
  src/components/stable/gux-radial-progress/tests/gux-radial-progress.service.spec.ts
Labels: backport

#577 feat(tests): adding new tool for manual accessibility testing
  package.json
  scripts/check-a11y.js
  scripts/list-checked-a11y-components.js
Labels: POC
