Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2021-11, with the labels that each got.

#521 fix(pagination): better handle invalid current page values
  src/components/stable/gux-pagination/gux-pagination.tsx
  src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap
  src/components/stable/gux-pagination/tests/gux-pagination.spec.ts
Labels: backport

#526 fix(gux-tabs-beta): fix gux-tab-beta console errors
  src/components/beta/gux-tabs-beta/gux-tab-list-beta/gux-tab-list-beta.tsx
Labels: backport

#530 fix(gux-icon): remap trade icon to use correct icon
  src/components/stable/gux-icon/icon-name-map.ts
Labels: simple review

#531 fix(gux-icon): remap trade icon to use correct icon
  src/components/stable/gux-icon/icon-name-map.ts
Labels: simple review, backport

#534 fix(input-range): small styling change
  src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.less
Labels: simple review, backport

#551 fix(css): global gux-sr-only is not used by components anymore
  src/components/stable/gux-calendar/gux-calendar.less
  src/components/stable/gux-datepicker/gux-datepicker.less
Labels: backport
