Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-08, with the labels that each got.

#854 fix(table): fixed sorting UI bugs
  src/components/beta/gux-table/example.html
  src/components/beta/gux-table/gux-sort-control/gux-sort-control.less
  src/components/beta/gux-table/gux-sort-control/gux-sort-control.tsx
  src/components/beta/gux-table/gux-sort-control/readme.md
  src/components/beta/gux-table/gux-sort-control/tests/__snapshots__/gux-sort-control.e2e.ts.snap
  src/components/beta/gux-table/gux-sort-control/tests/__snapshots__/gux-sort-control.spec.ts.snap
  src/components/beta/gux-table/gux-sort-control/tests/gux-sort-control.e2e.ts
  src/components/beta/gux-table/gux-sort-control/tests/gux-sort-control.markup.ts
  src/components/beta/gux-table/gux-sort-control/tests/gux-sort-control.spec.ts
  src/components/beta/gux-table/gux-table.light.less
  src/components/beta/gux-table/gux-table.tsx
  src/components/beta/gux-table/gux-table.types.ts
  src/components/beta/gux-table/i18n/en.json
  src/components/beta/gux-table/readme.md
  src/components/beta/gux-table/tests/__snapshots__/gux-table.e2e.ts.snap
  src/components/beta/gux-table/tests/gux-table.e2e.ts
Labels: new api

#864 chore(dependencies): updated dependencies to wanted
  docs/package-lock.json
  docs/package.json
  package-lock.json
  package.json
Labels: simple review

#870 feat(anchor-style): updated in table anchor styles
  src/components/beta/gux-visualization/readme.md
  src/style/examples/typography.html
  src/style/typography.less
Labels: simple review

#868 fix(v3-migration): added info on IListItem removal
  docs/migrations/v3/gux-list-legacy.md
Labels: simple review

#835 feat(gux-button-multi): add icon option to multi button
  src/components/stable/gux-button-multi/example.html
  src/components/stable/gux-button-multi/gux-button-multi.less
  src/components/stable/gux-button-multi/gux-button-multi.light.less
  src/components/stable/gux-button-multi/gux-button-multi.tsx
  src/components/stable/gux-button-multi/readme.md
  src/style/style.less
Labels: new api

#878 fix(dropdown-multi): addition of event when clearing options from dro…
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx
Labels: bug

#871 feat(form-field): form fields not work as expected in a disabled fiel…
  src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/tests/gux-pagination-items-per-page-beta.spec.ts
  src/components/stable/gux-dropdown/gux-dropdown.tsx
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx
  src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.tsx
  src/components/stable/gux-form-field/components/gux-form-field-color/tests/__snapshots__/gux-form-field-color.e2e.ts.snap
  src/components/stable/gux-form-field/components/gux-form-field-color/tests/__snapshots__/gux-form-field-color.spec.ts.snap
  src/components/stable/gux-form-field/components/gux-form-field-color/tests/gux-form-field-color.e2e.ts
  src/components/stable/gux-form-field/components/gux-form-field-color/tests/gux-form-field-color.spec.ts
  src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.less
  src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.tsx
  src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.e2e.ts.snap
  src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
  src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.less
  src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.tsx
  src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx
  src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx
  src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.tsx
  src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.tsx
  src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.tsx
  src/components/stable/gux-form-field/components/gux-form-field-textarea/gux-form-field-textarea.tsx
  src/utils/dom/calculate-input-disabled-state.ts
  src/utils/dom/on-input-disabled-state-change.ts
Labels: early feedback wanted

#867 feat(skip-links): added new skip-navigation component
  src/components/beta/gux-skip-navigation-list/example.html
  src/components/beta/gux-skip-navigation-list/gux-skip-navigation-item/gux-skip-navigation-item.less
  src/components/beta/gux-skip-navigation-list/gux-skip-navigation-item/gux-skip-navigation-item.tsx
  src/components/beta/gux-skip-navigation-list/gux-skip-navigation-item/readme.md
  src/components/beta/gux-skip-navigation-list/gux-skip-navigation-list.less
  src/components/beta/gux-skip-navigation-list/gux-skip-navigation-list.tsx
  src/components/beta/gux-skip-navigation-list/i18n/ar.json
  src/components/beta/gux-skip-navigation-list/i18n/cs.json
  src/components/beta/gux-skip-navigation-list/i18n/da.json
  src/components/beta/gux-skip-navigation-list/i18n/de.json
  src/components/beta/gux-skip-navigation-list/i18n/en.json
  src/components/beta/gux-skip-navigation-list/i18n/es-es.json
  src/components/beta/gux-skip-navigation-list/i18n/es.json
  src/components/beta/gux-skip-navigation-list/i18n/fi.json
  src/components/beta/gux-skip-navigation-list/i18n/fr-ca.json
  src/components/beta/gux-skip-navigation-list/i18n/fr.json
  src/components/beta/gux-skip-navigation-list/i18n/he.json
  src/components/beta/gux-skip-navigation-list/i18n/it.json
  src/components/beta/gux-skip-navigation-list/i18n/ja.json
  src/components/beta/gux-skip-navigation-list/i18n/ko.json
  src/components/beta/gux-skip-navigation-list/i18n/nl.json
  src/components/beta/gux-skip-navigation-list/i18n/no.json
  src/components/beta/gux-skip-navigation-list/i18n/pl.json
  src/components/beta/gux-skip-navigation-list/i18n/pt-br.json
  src/components/beta/gux-skip-navigation-list/i18n/pt-pt.json
  src/components/beta/gux-skip-navigation-list/i18n/ru.json
  src/components/beta/gux-skip-navigation-list/i18n/sv.json
  src/components/beta/gux-skip-navigation-list/i18n/th.json
  src/components/beta/gux-skip-navigation-list/i18n/tr.json
  src/components/beta/gux-skip-navigation-list/i18n/zh-cn.json
  src/components/beta/gux-skip-navigation-list/i18n/zh-tw.json
  src/components/beta/gux-skip-navigation-list/readme.md
  src/components/beta/gux-skip-navigation-list/tests/__snapshots__/gux-skip-navigation-list.e2e.ts.snap
  src/components/beta/gux-skip-navigation-list/tests/__snapshots__/gux-skip-navigation-list.spec.ts.snap
  src/components/beta/gux-skip-navigation-list/tests/gux-skip-navigation-list.e2e.ts
  src/components/beta/gux-skip-navigation-list/tests/gux-skip-navigation-list.spec.ts
  src/style/mixins.less
  src/style/typography.less
Labels: early feedback wanted, new api

#886 fix(translations): added new languages
  package.json
  scripts/create-non-en-i18n-files.js
  src/components/beta/gux-command-palette/i18n/he.json
  src/components/beta/gux-command-palette/i18n/pt-pt.json
  src/components/beta/gux-dismiss-button/i18n/he.json
  src/components/beta/gux-dismiss-button/i18n/pt-pt.json
  src/components/beta/gux-dropdown-v2/gux-listbox/i18n/he.json
  src/components/beta/gux-dropdown-v2/gux-listbox/i18n/pt-pt.json
  src/components/beta/gux-dropdown-v2/i18n/he.json
  src/components/beta/gux-dropdown-v2/i18n/pt-pt.json
  src/components/beta/gux-form-field-v2/components/gux-form-field-number/i18n/he.json
  src/components/beta/gux-form-field-v2/components/gux-form-field-number/i18n/pt-pt.json
  src/components/beta/gux-form-field-v2/helper-components/gux-form-field-input-clear-button/i18n/he.json
  src/components/beta/gux-form-field-v2/helper-components/gux-form-field-input-clear-button/i18n/pt-pt.json
  src/components/beta/gux-pagination-cursor/i18n/he.json
  src/components/beta/gux-pagination-cursor/i18n/pt-pt.json
  src/components/beta/gux-skip-navigation-list/i18n/he.json
  src/components/beta/gux-skip-navigation-list/i18n/pt-pt.json
  src/components/beta/gux-table/i18n/he.json
  src/components/beta/gux-table/i18n/pt-pt.json
  src/components/beta/gux-tabs-beta/i18n/he.json
  src/components/beta/gux-tabs-beta/i18n/pt-pt.json
  src/components/beta/gux-tag/i18n/he.json
  src/components/beta/gux-tag/i18n/pt-pt.json
  src/components/legacy/gux-spin-button-legacy/i18n/he.json
  src/components/legacy/gux-spin-button-legacy/i18n/pt-pt.json
  src/components/legacy/gux-text-field-legacy/i18n/he.json
  src/components/legacy/gux-text-field-legacy/i18n/pt-pt.json
  src/components/stable/gux-action-button/i18n/he.json
  src/components/stable/gux-action-button/i18n/pt-pt.json
  src/components/stable/gux-advanced-dropdown/i18n/he.json
  src/components/stable/gux-advanced-dropdown/i18n/pt-pt.json
  src/components/stable/gux-breadcrumbs/i18n/he.json
  src/components/stable/gux-breadcrumbs/i18n/pt-pt.json
  src/components/stable/gux-content-search/i18n/he.json
  src/components/stable/gux-content-search/i18n/pt-pt.json
  src/components/stable/gux-datepicker/i18n/he.json
  src/components/stable/gux-datepicker/i18n/pt-pt.json
  src/components/stable/gux-form-field/components/gux-input-color/i18n/he.json
  src/components/stable/gux-form-field/components/gux-input-color/i18n/pt-pt.json
  src/components/stable/gux-form-field/components/gux-input-number/i18n/he.json
  src/components/stable/gux-form-field/components/gux-input-number/i18n/pt-pt.json
  src/components/stable/gux-form-field/components/gux-input-search/i18n/he.json
  src/components/stable/gux-form-field/components/gux-input-search/i18n/pt-pt.json
  src/components/stable/gux-form-field/components/gux-input-text-like/i18n/he.json
  src/components/stable/gux-form-field/components/gux-input-text-like/i18n/pt-pt.json
  src/components/stable/gux-pagination/gux-pagination-buttons/i18n/he.json
  src/components/stable/gux-pagination/gux-pagination-buttons/i18n/pt-pt.json
  src/components/stable/gux-pagination/gux-pagination-item-counts/i18n/he.json
  src/components/stable/gux-pagination/gux-pagination-item-counts/i18n/pt-pt.json
  src/components/stable/gux-pagination/gux-pagination-items-per-page/i18n/he.json
  src/components/stable/gux-pagination/gux-pagination-items-per-page/i18n/pt-pt.json
  src/components/stable/gux-radial-loading/i18n/he.json
  src/components/stable/gux-radial-loading/i18n/pt-pt.json
  src/components/stable/gux-tabs/i18n/he.json
  src/components/stable/gux-tabs/i18n/pt-pt.json
  src/i18n/locales.json
  src/i18n/start-of-week.json
Labels: simple review, V2 maintenance

#882 fix(list): addition of styling for when false value is assigned to di…
  src/components/stable/gux-list/gux-list-item/gux-list-item.less
  src/components/stable/gux-list/gux-list-item/gux-list-item.tsx
Labels: bug

#890 style(form-field-search): change search icon to be 16px
  src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.less
Labels: simple review

#891 fix(dropdown): dropdown will now close if same value is reselected fr…
  src/components/stable/gux-dropdown/gux-dropdown.tsx
Labels: bug

#895 fix(color-palette): update Red 70 color to match Spark color system
  src/style/color-palette.less
Labels: simple review

#881 style(checkbox): align error message to label instead of input
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.less
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.e2e.ts.snap
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.spec.ts.snap
Labels: simple review, UX Input Needed

#849 [COMUI-1085] Add new components to display dates and times
  package.json
  src/components/beta/gux-date-time/example.html
  src/components/beta/gux-date-time/gux-date-time.tsx
  src/components/beta/gux-date-time/readme.md
  src/components/beta/gux-date-time/tests/__snapshots__/gux-date-time.e2e.ts.snap
  src/components/beta/gux-date-time/tests/__snapshots__/gux-date-time.spec.ts.snap
  src/components/beta/gux-date-time/tests/gux-date-time.e2e.ts
  src/components/beta/gux-date-time/tests/gux-date-time.spec.ts
  src/components/beta/gux-date/example.html
  src/components/beta/gux-date/gux-date.tsx
  src/components/beta/gux-date/readme.md
  src/components/beta/gux-date/tests/__snapshots__/gux-date.e2e.ts.snap
  src/components/beta/gux-date/tests/__snapshots__/gux-date.spec.ts.snap
  src/components/beta/gux-date/tests/gux-date.e2e.ts
  src/components/beta/gux-date/tests/gux-date.spec.ts
  src/components/beta/gux-time/example.html
  src/components/beta/gux-time/gux-time.tsx
  src/components/beta/gux-time/readme.md
  src/components/beta/gux-time/tests/__snapshots__/gux-time.e2e.ts.snap
  src/components/beta/gux-time/tests/__snapshots__/gux-time.spec.ts.snap
  src/components/beta/gux-time/tests/gux-time.e2e.ts
  src/components/beta/gux-time/tests/gux-time.spec.ts
  src/i18n/DateTimeFormatter.ts
Labels: new api

#897 fix(dropdown_v2): added missing if guard
  src/components/beta/gux-dropdown-v2/gux-dropdown-v2.tsx
Labels: simple review, backport

#876 (fix) - Tooltip appears for button when focus not on button, Does not get dismissed by clicking outside
  src/components/stable/gux-tooltip/gux-tooltip.less
  src/components/stable/gux-tooltip/gux-tooltip.tsx
Labels: bug

#900 style(radio): align error label with input label
  src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.less
  src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx
  src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.e2e.ts.snap
  src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.spec.ts.snap
Labels: simple review

#902 fix(option/dropdown-option): fix where disabled="false" was creating …
  src/components/stable/gux-advanced-dropdown/dropdown-option/gux-dropdown-option.less
  src/components/stable/gux-listbox/gux-option/gux-option.less
Labels: bug

#859 feat(blank-state) - addition of blank-state component
  src/components/beta/gux-blank-state/example.html
  src/components/beta/gux-blank-state/gux-blank-state-constants.ts
  src/components/beta/gux-blank-state/gux-blank-state.less
  src/components/beta/gux-blank-state/gux-blank-state.tsx
  src/components/beta/gux-blank-state/gux-blank-state.types.ts
  src/components/beta/gux-blank-state/readme.md
  src/components/beta/gux-blank-state/tests/__snapshots__/gux-blank-state.spec.ts.snap
  src/components/beta/gux-blank-state/tests/gux-blank-state.e2e.ts
  src/components/beta/gux-blank-state/tests/gux-blank-state.spec.ts
  src/components/beta/gux-button-slot/gux-button-slot.tsx
  src/components/beta/gux-button-slot/readme.md
Labels: new api
