Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-10, with the labels that each got.

#935 feat(button) - Addition of danger accent to gux-button, gux-action-button
  src/components/beta/gux-button-slot/example.html
  src/components/beta/gux-button-slot/gux-button-slot.less
  src/components/beta/gux-button-slot/readme.md
  src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.e2e.ts.snap
  src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.spec.ts.snap
  src/components/beta/gux-button-slot/tests/gux-button-slot.e2e.ts
  src/components/beta/gux-button-slot/tests/gux-button-slot.spec.ts
  src/components/legacy/gux-action-button-legacy/gux-action-button.tsx
  src/components/legacy/gux-action-button-legacy/gux-button.types.ts
  src/components/legacy/gux-action-button-legacy/readme.md
  src/components/legacy/gux-button-multi-legacy/gux-button-multi.tsx
  src/components/legacy/gux-button-multi-legacy/readme.md
  src/components/stable/gux-action-button/example.html
  src/components/stable/gux-action-button/gux-action-button.tsx
  src/components/stable/gux-action-button/readme.md
  src/components/stable/gux-button-multi/gux-button-multi.tsx
  src/components/stable/gux-button-multi/readme.md
  src/components/stable/gux-button/example.html
  src/components/stable/gux-button/gux-button.less
  src/components/stable/gux-button/gux-button.tsx
  src/components/stable/gux-button/gux-button.types.ts
  src/components/stable/gux-button/readme.md
  src/components/stable/gux-button/tests/__snapshots__/gux-button.e2e.ts.snap
  src/components/stable/gux-button/tests/__snapshots__/gux-button.spec.ts.snap
  src/components/stable/gux-button/tests/gux-button.e2e.ts
  src/components/stable/gux-button/tests/gux-button.spec.ts
Labels: simple review, ux review

#940 chore(dependencies): updated dependencies
  package-lock.json
  package.json
Labels: simple review

#933 fix(gux-table): use percentage widths for resizable columns to alter …
  src/components/beta/gux-table/gux-table.tsx
Labels: bug

#944 chore(dependencies): updated all dependencies to wanted
  docs/package-lock.json
  docs/package.json
  package-lock.json
  package.json
Labels: simple review

#946 ci(ux-review): add additional reviews, draft of process reminder
  .github/workflows/ux-review.yml
Labels: ux review

#939 feat(dropdown-multi): addition of collapsed and expanded events
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx
  src/components/beta/gux-dropdown-multi/readme.md
  src/components/stable/gux-popup/gux-popup.tsx
  src/components/stable/gux-popup/readme.md
Labels: simple review

#957 fix(form-field-search): addition of guxForceUpdate to form-field-search
  src/components/stable/gux-form-field/components/gux-form-field-search/example.html
  src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.tsx
  src/components/stable/gux-form-field/components/gux-form-field-search/readme.md
Labels: bug

#947 feat(dropdown): added loading state
  src/components/beta/gux-dropdown-multi/example.html
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx
  src/components/beta/gux-dropdown-multi/readme.md
  src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/readme.md
  src/components/beta/gux-pagination-beta/readme.md
  src/components/stable/gux-dropdown/example.html
  src/components/stable/gux-dropdown/gux-dropdown.tsx
  src/components/stable/gux-dropdown/readme.md
  src/components/stable/gux-listbox-multi/gux-listbox-multi.less
  src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
  src/components/stable/gux-listbox-multi/i18n/en.json
  src/components/stable/gux-listbox-multi/readme.md
  src/components/stable/gux-listbox/gux-listbox.less
  src/components/stable/gux-listbox/gux-listbox.tsx
  src/components/stable/gux-listbox/i18n/en.json
  src/components/stable/gux-listbox/readme.md
  src/components/stable/gux-pagination/gux-pagination-items-per-page/readme.md
  src/components/stable/gux-pagination/readme.md
  src/components/stable/gux-radial-loading/readme.md
  src/i18n/translations/en.json
Labels: new api
