Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-12, with the labels that each got.

#1041 fix(table-toolbar): add delegatesFocus to custom action component
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
Labels: simple review

#1040 feat(gux-toggle): show pointer when hovering toggle component
  src/components/stable/gux-toggle/gux-toggle.less
Labels: ux review

#857 feat(context-menu): add new webcomponent
  src/components/beta/gux-button-slot/readme.md
  src/components/beta/gux-context-menu/example.html
  src/components/beta/gux-context-menu/gux-context-menu.less
  src/components/beta/gux-context-menu/gux-context-menu.tsx
  src/components/beta/gux-context-menu/i18n/en.json
  src/components/beta/gux-context-menu/readme.md
  src/components/beta/gux-context-menu/tests/__snapshots__/gux-context-menu.spec.ts.snap
  src/components/beta/gux-context-menu/tests/gux-context-menu.e2e.ts
  src/components/beta/gux-context-menu/tests/gux-context-menu.spec.ts
  src/components/stable/gux-icon/readme.md
  src/components/stable/gux-list/gux-list.tsx
  src/components/stable/gux-list/readme.md
  src/components/stable/gux-popup/readme.md
  src/i18n/translations/en.json
  src/i18n/translations/fi.json
Labels: early feedback wanted, new api
