Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-01, with the labels that each got.

#587 fix(gux-modal): fix max-height style
  src/components/stable/gux-modal/gux-modal.less
Labels: backport

#599 fix(gux-popup): fix popup alignment
  src/components/beta/gux-popup/gux-popup.tsx
Labels: simple review

#600 fix(gux-popup): fix alignment of popup, backport to v2
  src/components/beta/gux-popup/gux-popup.tsx
Labels: simple review, backport

#579 feat(radial-progress): now using Stencil functional components intern…
  src/components/stable/gux-radial-progress/gux-radial-progress.functional.less
  src/components/stable/gux-radial-progress/gux-radial-progress.functional.tsx
  src/components/stable/gux-radial-progress/gux-radial-progress.less
  src/components/stable/gux-radial-progress/gux-radial-progress.tsx
  src/components/stable/gux-radial-progress/tests/gux-radial-progress.spec.ts
Labels: simple review

#610 fix(gux-tab-panel-beta): fixed tabpanel outline shown on click in safari
  src/components/beta/gux-tabs-beta/gux-tab-panel-beta/gux-tab-panel-beta.less
Labels: backport

#609 fix(gux-dropdown): gux-dropdown within a gux-panel bug
  src/components/stable/gux-dropdown/gux-dropdown.less
  src/components/stable/gux-dropdown/gux-dropdown.tsx
Labels: backport
