Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-05, with the labels that each got.

#737 fix(typo): fixed icon name typo
  docs/src/utils/generateIcons.js
  src/components/stable/gux-icon/icons/roster-instagram-disable.svg
Labels: simple review

#738 fix(typo): fixed icon name typo
  docs/src/utils/generateIcons.js
  src/components/stable/gux-icon/icons/roster-instagram-disable.svg
Labels: simple review, backport

#744 docs(popup): removed popup example as it is an internal component
  src/components/stable/gux-popup/example.html
Labels: simple review

#756 fix(gux-dropdown-v2): fix stacking context bug
  src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less
  src/components/beta/gux-popup/gux-popup.less
Labels: backport

#762 fix(time-picker): now using event.key so numpad works on firefox and …
  src/components/beta/gux-time-picker/gux-time-picker.tsx
  src/components/beta/gux-time-picker/tests/gux-time-picker.spec.ts
Labels: backport

#774 docs(readme): removed IE11 support info from readme
  README.md
Labels: simple review
