Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-03, with the labels that each got.

#650 fix(gux-tabs-beta): long text no longer overflows tab tooltip backport
  src/components/beta/gux-tabs-beta/example.html
  src/components/beta/gux-tooltip-title/gux-tooltip-title.less
Labels: backport

#663 docs(vue-2): updated example to show fix to COMUI-685
  playground/vue-2/src/components/HelloWorld.vue
Labels: simple review

#665 Com UI 747
  playground/vue-2/src/components/HelloWorld.vue
Labels: simple review

#670 fix(gux-modal): new trap-focus implementation (backport)
  package-lock.json
  package.json
  src/components/stable/gux-modal/example.html
  src/components/stable/gux-modal/gux-modal.tsx
  src/components/stable/gux-modal/tests/__snapshots__/gux-modal.e2e.ts.snap
  src/components/stable/gux-modal/tests/__snapshots__/gux-modal.spec.ts.snap
  src/components/stable/gux-modal/tests/gux-modal.e2e.ts
  src/components/stable/gux-modal/tests/gux-modal.spec.ts
Labels: backport

#678 fix(axe-live): fixed call to axe-live in docs
  docs/src/component-viewer/app.js
Labels: simple review

#679 fix(axe-live): fixed call to axe-live in docs
  docs/src/component-viewer/app.js
Labels: simple review, backport

#680 fix(gux-input-range): round tooltip position to prevent snapshot inconsistencies
  src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.tsx
  src/components/stable/gux-form-field/tests/__snapshots__/gux-form-field.e2e.ts.snap
Labels: backport

#681 fix(dropdown-v2): stopped emitting internal focus events outside the …
  playground/angular-v12/src/app/app.component.html
  playground/angular-v12/src/app/app.component.less
  playground/angular-v12/src/app/app.component.ts
  playground/angular-v12/src/data/country-list.ts
  playground/angular-v12/src/data/pet-list.ts
  src/components/beta/gux-dropdown-v2/gux-dropdown-v2.tsx
Labels: backport

#682 feat(form-field): explicitly set shadowDOM to false
  src/components/stable/gux-form-field/gux-form-field.tsx
Labels: simple review

#689 feat(gux-icon): added shield-solid and shield-outline icons
  docs/src/utils/generateIcons.js
  src/components/stable/gux-icon/icons/phone-call-directory.svg
  src/components/stable/gux-icon/icons/shield-outline.svg
  src/components/stable/gux-icon/icons/shield-solid.svg
  src/components/stable/gux-icon/icons/sms-close.svg
  src/components/stable/gux-icon/icons/toolbar-phone-disable.svg
  src/components/stable/gux-icon/icons/user-interactions-disable.svg
  src/components/stable/gux-icon/icons/window-expand.svg
  svgo.config.js
Labels: backport

#685 Merge pull request #672 from MyPureCloud/feature/COMUI-954
  src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.tsx
  src/components/stable/gux-advanced-dropdown/tests/gux-advanced-dropdown.e2e.ts
Labels: backport

#693 docs(jest): added known issue with jest CLI argument
  CONTRIBUTING.md
Labels: simple review
