Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-02, with the labels that each got.

#611 feat(icon): added new icons
  docs/src/utils/generateIcons.js
  package.json
  src/components/stable/gux-icon/icons/8x8-alt.svg
  src/components/stable/gux-icon/icons/8x8.svg
  src/components/stable/gux-icon/icons/calendar-add.svg
  src/components/stable/gux-icon/icons/chevron-double-down.svg
  src/components/stable/gux-icon/icons/chevron-double-up.svg
  src/components/stable/gux-icon/icons/clipboard-success.svg
  src/components/stable/gux-icon/icons/face-empathy.svg
  src/components/stable/gux-icon/icons/flag.svg
  src/components/stable/gux-icon/icons/lock-hold.svg
  src/components/stable/gux-icon/icons/phone-success.svg
  src/components/stable/gux-icon/icons/subtract.svg
  svgo.config.js
Labels: simple review

#612 feat(icon): added new icons
  docs/src/utils/generateIcons.js
  package.json
  src/components/stable/gux-icon/icons/8x8-alt.svg
  src/components/stable/gux-icon/icons/8x8.svg
  src/components/stable/gux-icon/icons/calendar-add.svg
  src/components/stable/gux-icon/icons/chevron-double-down.svg
  src/components/stable/gux-icon/icons/chevron-double-up.svg
  src/components/stable/gux-icon/icons/clipboard-success.svg
  src/components/stable/gux-icon/icons/face-empathy.svg
  src/components/stable/gux-icon/icons/flag.svg
  src/components/stable/gux-icon/icons/lock-hold.svg
  src/components/stable/gux-icon/icons/phone-success.svg
  src/components/stable/gux-icon/icons/subtract.svg
  svgo.config.js
Labels: simple review, backport

#613 fix(button): added specificity to secondary button css
  src/components/stable/gux-button/gux-button.less
Labels: V2 maintenance

#619 fix(scripts): fixed generate-versions-file script, backport to v2
  Jenkinsfile
  package-lock.json
  package.json
  scripts/generate-versions-file
  scripts/generate-versions-file.mjs
Labels: backport
