Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2022-09, with the labels that each got.

#905 fix(knockout): added knockout playground
  playground/knockout-3/index.html
  playground/knockout-3/package-lock.json
  playground/knockout-3/package.json
Labels: simple review

#907 build(stylelint): moved config to seperate file
  package.json
  src/components/stable/gux-tooltip/gux-tooltip.less
  stylelint.config.js
Labels: simple review

#906 fix(form-fields): updated checkbox and radio icons
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.less
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.light.less
  src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.less
  src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.light.less
  src/components/stable/gux-icon/icons/checkbox-active.svg
  src/components/stable/gux-icon/icons/checkbox-partial.svg
  src/components/stable/gux-icon/icons/checkbox.svg
  src/components/stable/gux-icon/icons/radio-active.svg
  src/components/stable/gux-icon/icons/radio.svg
Labels: simple review

#910 chore(dependencies): updated dependencies
  package-lock.json
  package.json
Labels: simple review

#911 fix(script): updated list-i18n-files script to give clearer output
  scripts/list-i18n-files.js
Labels: simple review

#901 feat(announce): added new component
  src/components/beta/gux-announce/a11yManualChecklist.md
  src/components/beta/gux-announce/example.html
  src/components/beta/gux-announce/gux-announce.less
  src/components/beta/gux-announce/gux-announce.tsx
  src/components/beta/gux-announce/gux-announce.types.ts
  src/components/beta/gux-announce/readme.md
Labels: new api

#872 ci(github workflow): add UX reviewers when the 'ux review' label is added to the PR
  .github/workflows/ux-review.yml
Labels: ci-testing

#915 feat(gux-toggle): enable preventDefault on check events
  src/components/stable/gux-toggle/gux-toggle.tsx
  src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
Labels: simple review

#916 V2: feat(gux-toggle): enable preventDefault on check events
  src/components/stable/gux-toggle/gux-toggle.tsx
  src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
Labels: simple review, backport

#912 fix(calendar): calendar skipping month for some dates
  src/components/stable/gux-calendar/gux-calendar.tsx
  src/components/stable/gux-calendar/tests/gux-calendar.e2e.ts
Labels: bug

#917 fix(gux-datepicker): fix input, state, and focus bugs
  src/components/stable/gux-datepicker/gux-datepicker.less
  src/components/stable/gux-datepicker/gux-datepicker.tsx
  src/components/stable/gux-datepicker/readme.md
  src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap
Labels: bug

#919 fix(sort-control): utilising :has selector to apply padding to sort control.
  src/components/beta/gux-table/gux-table.light.less
Labels: bug

#918 feat(translations): moved translations out of component folders
  .husky/pre-commit
  package.json
  scripts/build-i18n.js
  scripts/update-en-i18n.js
  src/i18n/translations/ar.json
  src/i18n/translations/cs.json
  src/i18n/translations/da.json
  src/i18n/translations/de.json
  src/i18n/translations/en.json
  src/i18n/translations/es-es.json
  src/i18n/translations/es.json
  src/i18n/translations/fi.json
  src/i18n/translations/fr-ca.json
  src/i18n/translations/fr.json
  src/i18n/translations/he.json
  src/i18n/translations/it.json
  src/i18n/translations/ja.json
  src/i18n/translations/ko.json
  src/i18n/translations/nl.json
  src/i18n/translations/no.json
  src/i18n/translations/pl.json
  src/i18n/translations/pt-br.json
  src/i18n/translations/pt-pt.json
  src/i18n/translations/ru.json
  src/i18n/translations/sv.json
  src/i18n/translations/th.json
  src/i18n/translations/tr.json
  src/i18n/translations/zh-cn.json
  src/i18n/translations/zh-tw.json
Labels: early feedback wanted

#927 feat(icon): added badge-x icon
  docs/src/utils/generateIcons.js
  src/components/stable/gux-icon/icons/badge-x.svg
Labels: simple review, backport

#928 chore(dependencies): updated all dependencies to wanted
  docs/package-lock.json
  docs/package.json
  package-lock.json
  package.json
  src/components/stable/gux-form-field/components/gux-form-field-number/readme.md
Labels: simple review

#931 fix(version): bumping version after failed automated bump broke build
  package-lock.json
  package.json
Labels: simple review

#923 fix(option): remove whitespace from text of gux-options.
  src/components/stable/gux-dropdown/gux-dropdown.tsx
  src/components/stable/gux-listbox/gux-listbox.service.ts
  src/components/stable/gux-listbox/gux-listbox.tsx
Labels: bug

#938 fix(toggle): fixed check event detail
  src/components/stable/gux-toggle/gux-toggle.tsx
Labels: simple review

#936 Feature/com UI 1224
  src/components/stable/gux-popup/gux-popup.tsx
  src/i18n/translations/ar.json
  src/i18n/translations/cs.json
  src/i18n/translations/da.json
  src/i18n/translations/de.json
  src/i18n/translations/es-es.json
  src/i18n/translations/es.json
  src/i18n/translations/fi.json
  src/i18n/translations/fr-ca.json
  src/i18n/translations/fr.json
  src/i18n/translations/he.json
  src/i18n/translations/it.json
  src/i18n/translations/ja.json
  src/i18n/translations/ko.json
  src/i18n/translations/nl.json
  src/i18n/translations/no.json
  src/i18n/translations/pl.json
  src/i18n/translations/pt-br.json
  src/i18n/translations/pt-pt.json
  src/i18n/translations/ru.json
  src/i18n/translations/sv.json
  src/i18n/translations/th.json
  src/i18n/translations/tr.json
  src/i18n/translations/zh-cn.json
  src/i18n/translations/zh-tw.json
Labels: simple review
