Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-05, with the labels that each got.

#1237 fix(gux-dropdown): truncate long text and show tooltip
  packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/tests/__snapshots__/gux-dropdown-multi.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/readme.md
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/tests/__snapshots__/gux-pagination-items-per-page-beta.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/readme.md
  packages/genesys-spark-components/src/components/beta/gux-phone-input/readme.md
  packages/genesys-spark-components/src/components/beta/gux-truncate/readme.md
  packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.less
  packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
  packages/genesys-spark-components/src/components/stable/gux-dropdown/readme.md
  packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/__snapshots__/gux-dropdown.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.less
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option/gux-option.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/option-defaults.less
  packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-pagination/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap
Labels: ux review

#1214 feat(button): allow list to exceed width of button
  packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.less
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.tsx
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/readme.md
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/tests/__snapshots__/gux-popup-beta.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.less
  packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.less
  packages/genesys-spark-components/src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less
  packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.less
  packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.less
Labels: simple review

#1267 perf(popover): allow popover to search shadowRoot
  packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
Labels: simple review

#1270 build(jenkins): remove files committed by Jenkins in error
  deploy/infra/build_env.json
  deploy/infra/pipeline.d/build.json
Labels: simple review

#1271 fix(date-picker): add above label positioning
  packages/genesys-spark-components/src/components/stable/gux-datepicker/example.html
  packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.less
  packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx
  packages/genesys-spark-components/src/components/stable/gux-datepicker/readme.md
Labels: bug

#1279 feat(icon) - add fa/custom icons to GuxIconIconName type
  packages/genesys-spark-components/scripts/generate-gux-icon-types-file.js
  packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.types.ts
Labels: simple review

#1274 perf(form-field) - Improve error messaging
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/gux-form-field.service.ts
Labels: simple review

#1286 fix(time-picker): arabic now uses 24h layout
  packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.service.tsx
Labels: simple review

#1291 fix(tab-advanced-list): watch for dynamic changes to allowSort prop
  packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced-list/gux-tab-advanced-list.tsx
Labels: bug

#1300 refactor(services): fixed service file extensions
  packages/genesys-spark-components/src/components/beta/gux-column-manager/gux-column-manager.service.ts
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar.service.ts
  packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.service.ts
  packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.type.ts
  packages/genesys-spark-components/src/components/stable/gux-list/gux-list.service.ts
Labels: simple review
