Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-06, with the labels that each got.

#1315 feat(icon): add new icons
  packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.types.ts
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/circle-check-solid.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/circle-info-solid.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/hexagon-exclamation-solid.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/triangle-exclamation-solid.svg
  web-apps/genesys-spark-examples/src/utils/generateFontAwesomeIcons.js
Labels: simple review

#1317 chore(github-action): fix formatting in UX review Github Action
  .github/workflows/ux-review.yml
Labels: ux review

#1314 fix(table-toolbar): unobserve single element instead of unobserving all elements.
  packages/genesys-spark-components/src/utils/decorator/on-mutation.ts
  packages/genesys-spark-components/src/utils/decorator/on-resize.ts
Labels: bug

#1333 fix(table-toolbar): add pointer events none to disabled elements.
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.less
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.tsx
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.less
Labels: bug, simple review

#1341 docs(readme): update documentation links
  README.md
Labels: simple review

#1339 fix(pagination): add fixed width to items per page dropdown
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/gux-pagination-items-per-page-beta.less
  packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/gux-pagination-items-per-page.less
Labels: bug
