Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-08, with the labels that each got.

#1437 docs(migration-guide): update migration docs for toast components
  packages/genesys-spark-components/documentation/migrations/v4/gux-action-toast-legacy.md
  packages/genesys-spark-components/documentation/migrations/v4/gux-notification-toast-legacy.md
  packages/genesys-spark-components/documentation/migrations/v4/gux-simple-toast-legacy.md
  packages/genesys-spark-components/documentation/migrations/v4/readme.md
Labels: V4 Release Component Updates

#1356 feat(gux-time-zone-picker-beta): add a time zone picker component
  package-lock.json
  packages/genesys-spark-components/package.json
  packages/genesys-spark-components/src/components/beta/gux-phone-input/readme.md
  packages/genesys-spark-components/src/components/beta/gux-tag/readme.md
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/a11yManualChecklist.md
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/example.html
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/generic-zones.ts
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.less
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.tsx
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.types.ts
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/i18n/en.json
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/readme.md
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/__snapshots__/gux-time-zone-picker.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/gux-time-zone-picker.e2e.ts
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/gux-time-zone-picker.spec.ts
  packages/genesys-spark-components/src/components/stable/gux-dropdown/readme.md
  packages/genesys-spark-components/src/components/stable/gux-icon/readme.md
  packages/genesys-spark-components/src/components/stable/gux-list/gux-list-divider/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/readme.md
  packages/genesys-spark-components/src/components/stable/gux-tabs/tests/__snapshots__/gux-tabs.e2e.ts.snap
  packages/genesys-spark-components/src/i18n/translations/en.json
Labels: UX Input Needed

#1444 fix(popup): fix floating ui implementation
  packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.tsx
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/readme.md
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/tests/__snapshots__/gux-popup-beta.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx
  packages/genesys-spark-components/src/components/stable/gux-action-button/tests/__snapshots__/gux-action-button.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less
  packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx
  packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.less
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/readme.md
Labels: bug

#1448 chore(pagination-cursor): adopting tokens and converting to scss
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.less
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.scss
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.tsx
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/__snapshots__/gux-pagination-cursor.spec.ts.snap
  packages/genesys-spark-components/src/style/style.less
Labels: V4 Release Component Updates

#1310 fix(table-toolbar): addition of tooltip when actions are in icon-only mode.
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-action/readme.md
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/readme.md
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.tsx
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/readme.md
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/readme.md
  packages/genesys-spark-components/src/components/beta/gux-table-toolbar/tests/__snapshots__/gux-table-toolbar.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-tooltip-title/readme.md
  packages/genesys-spark-components/src/components/stable/gux-tooltip/readme.md
Labels: bug

#1401 docs(migration) - update tooltip migration guide.
  packages/genesys-spark-components/documentation/migrations/v4/readme.md
Labels: V4 Release Component Updates

#1442 style(inline-alert): adding missing tokens
  packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.scss
  packages/genesys-spark-components/src/components/stable/gux-alert/readme.md
Labels: V4 Release Component Updates

#1301 refactor(rating): component reskin
  packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.scss
  packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.tsx
  packages/genesys-spark-components/src/components/stable/gux-rating/readme.md
Labels: V4 Release Component Updates

#1459 refactor(rating): remove less file
  packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.less
Labels: simple review, V4 Release Component Updates

#1468 fix(gux-icon): prevent updates to svgHtml if baseSvgHtml is not set
  packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.tsx
Labels: backport

#1472 fix(popover): find-element-by-id tries to call getElementById non-doc…
  packages/genesys-spark-components/src/utils/dom/find-element-by-id.ts
Labels: backport

#1469 feat(gux-popup-beta): hide popup when target element goes out of view
  packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.scss
  packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.tsx
Labels: backport

#1470 feat(icons): various requested icons
  packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.types.ts
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/file-pen-question.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/filter-notification.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/list-alphabetical-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/list-roman-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/alarm-clock-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/alarm-snooze-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/backward-step-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/bell-on-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/bell-slash-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/face-frown-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/face-frown-solid.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/face-laugh-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/face-laugh-solid.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/forward-step-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/pause-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/play-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/stop-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/subscript-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/superscript-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/volume-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/volume-xmark-regular.svg
  web-apps/genesys-spark-examples/src/utils/generateFontAwesomeIcons.js
Labels: backport

#1477 feat(time-picker) - migration from beta to stable
  packages/genesys-spark-components/documentation/migrations/v4/readme.md
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/example.html
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/gux-form-field-time-picker.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/readme.md
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/tests/__snapshots__/gux-form-field-time-picker.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/tests/__snapshots__/gux-form-field-time-picker.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/tests/gux-form-field-time-picker.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/tests/gux-form-field-time-picker.spec.ts
  packages/genesys-spark-components/src/components/stable/gux-form-field/gux-form-field.service.ts
  packages/genesys-spark-components/src/components/stable/gux-list/gux-list-item/readme.md
  packages/genesys-spark-components/src/components/stable/gux-list/readme.md
  packages/genesys-spark-components/src/components/stable/gux-popup/readme.md
  packages/genesys-spark-components/src/components/stable/gux-time-picker/example.html
  packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.less
  packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.service.ts
  packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.tsx
  packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.type.ts
  packages/genesys-spark-components/src/components/stable/gux-time-picker/i18n/en.json
  packages/genesys-spark-components/src/components/stable/gux-time-picker/readme.md
  packages/genesys-spark-components/src/components/stable/gux-time-picker/tests/__snapshots__/gux-time-picker.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-time-picker/tests/gux-time-picker.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-time-picker/tests/gux-time-picker.service.spec.ts
  packages/genesys-spark-components/src/components/stable/gux-time-picker/tests/gux-time-picker.spec.ts
  packages/genesys-spark-components/src/i18n/translations/en.json
  packages/genesys-spark-components/src/utils/dom/on-attribute-change.ts
Labels: V4 Release Component Updates

#1485 feat(listbox): made empty message configurable
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx
Labels: backport

#1482 feat(icon): icons requested in sprint gds23-2
  packages/genesys-spark-components/src/components/stable/gux-icon/example.html
  packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.types.ts
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/font-regular-highlight.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/arrows-to-circle-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/award-solid.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/diagram-nested-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/file-exclamation-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/hand-back-point-right-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/list-radio-clean-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/pen-slash-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/regular-user-circle-arrow-left.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/readme.md
  web-apps/genesys-spark-examples/src/utils/generateFontAwesomeIcons.js
Labels: backport
