Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-02, with the labels that each got.

#1022 feat(table-toolbar) - updates to design / bug fixes
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.less
  src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.less
  src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.tsx
  src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/readme.md
  src/components/beta/gux-table-toolbar/gux-table-toolbar.less
  src/components/beta/gux-table-toolbar/gux-table-toolbar.service.tsx
  src/components/beta/gux-table-toolbar/gux-table-toolbar.tsx
  src/components/beta/gux-table-toolbar/tests/__snapshots__/gux-table-toolbar.spec.ts.snap
  src/utils/dom/get-slot.ts
Labels: bug

#1073 fix(dropdown-multi): addition of mutation observer to dropdown-multi
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx
Labels: bug

#1134 fix(column-manager): checkbox events dispatched on (de)select all che…
  src/components/beta/gux-column-manager/example.html
  src/components/beta/gux-column-manager/gux-column-manager.service.tsx
Labels: new api

#1105 feat(gux-icon): add requested icons
  docs/src/utils/generateFontAwesomeIcons.js
  docs/webpack.config.js
  src/components/stable/gux-icon/example.html
  src/components/stable/gux-icon/icons/fa/1-regular.svg
  src/components/stable/gux-icon/icons/fa/arrow-down-wide-short-regular.svg
  src/components/stable/gux-icon/icons/fa/arrows-rotate-solid.svg
  src/components/stable/gux-icon/icons/fa/ban-regular.svg
  src/components/stable/gux-icon/icons/fa/book-regular.svg
  src/components/stable/gux-icon/icons/fa/briefcase-regular.svg
  src/components/stable/gux-icon/icons/fa/bullseye-regular.svg
  src/components/stable/gux-icon/icons/fa/calendar-days-regular.svg
  src/components/stable/gux-icon/icons/fa/circle-check-regular.svg
  src/components/stable/gux-icon/icons/fa/circle-xmark-regular.svg
  src/components/stable/gux-icon/icons/fa/clock-nine-regular.svg
  src/components/stable/gux-icon/icons/fa/clock-rotate-left-regular.svg
  src/components/stable/gux-icon/icons/fa/comments-regular.svg
  src/components/stable/gux-icon/icons/fa/cube-regular.svg
  src/components/stable/gux-icon/icons/fa/database-regular.svg
  src/components/stable/gux-icon/icons/fa/diamond-regular.svg
  src/components/stable/gux-icon/icons/fa/draw-circle-solid.svg
  src/components/stable/gux-icon/icons/fa/file-chart-pie-regular.svg
  src/components/stable/gux-icon/icons/fa/font-regular.svg
  src/components/stable/gux-icon/icons/fa/gears-regular.svg
  src/components/stable/gux-icon/icons/fa/gem-regular.svg
  src/components/stable/gux-icon/icons/fa/hourglass-start-regular.svg
  src/components/stable/gux-icon/icons/fa/infinity-regular.svg
  src/components/stable/gux-icon/icons/fa/language-regular.svg
  src/components/stable/gux-icon/icons/fa/life-ring-regular.svg
  src/components/stable/gux-icon/icons/fa/link-horizontal-slash-regular.svg
  src/components/stable/gux-icon/icons/fa/link-horizontal-solid.svg
  src/components/stable/gux-icon/icons/fa/list-ol-regular.svg
  src/components/stable/gux-icon/icons/fa/memo-circle-check-regular.svg
  src/components/stable/gux-icon/icons/fa/message-regular.svg
  src/components/stable/gux-icon/icons/fa/money-bill-regular.svg
  src/components/stable/gux-icon/icons/fa/rectangle-list-regular.svg
  src/components/stable/gux-icon/icons/fa/right-to-bracket-regular.svg
  src/components/stable/gux-icon/icons/fa/road-regular.svg
  src/components/stable/gux-icon/icons/fa/share-regular.svg
  src/components/stable/gux-icon/icons/fa/shuffle-regular.svg
  src/components/stable/gux-icon/icons/fa/sigma-regular.svg
  src/components/stable/gux-icon/icons/fa/signs-post-regular.svg
  src/components/stable/gux-icon/icons/fa/sitemap-regular.svg
  src/components/stable/gux-icon/icons/fa/ticket-regular.svg
Labels: ux review

#1151 feat(tooltip): addition of findElementByID util to tooltip
  src/components/stable/gux-tooltip/gux-tooltip.tsx
Labels: simple review
