Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-07, with the labels that each got.

#1332 feat(pagination-cursor): updating design with two layouts and optiona…
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/example.html
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.less
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.tsx
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/__snapshots__/gux-pagination-cursor.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/__snapshots__/gux-pagination-cursor.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/gux-pagination-cursor.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/gux-pagination-cursor.spec.ts
Labels: ux review

#1302 feat(phone-input): modifying behavior to more closely match intl-tel-…
  packages/genesys-spark-components/src/components/beta/gux-phone-input/components/gux-region-icon/gux-region-icon.tsx
  packages/genesys-spark-components/src/components/beta/gux-phone-input/components/gux-region-icon/readme.md
  packages/genesys-spark-components/src/components/beta/gux-phone-input/example.html
  packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.less
  packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.tsx
  packages/genesys-spark-components/src/components/beta/gux-phone-input/i18n/en.json
  packages/genesys-spark-components/src/components/beta/gux-phone-input/readme.md
  packages/genesys-spark-components/src/components/beta/gux-phone-input/services/RegionCountryCodeMap.ts
  packages/genesys-spark-components/src/components/beta/gux-phone-input/tests/__snapshots__/gux-phone-input.e2e.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-phone-input/tests/gux-phone-input.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/example.html
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/gux-form-field-phone.tsx
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/i18n/en.json
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/readme.md
  packages/genesys-spark-components/src/i18n/translations/en.json
Labels: UX Approved

#1294 refactor(restyle): prepare card component for v4 restyle
  package-lock.json
  packages/genesys-spark-components/src/components/beta/gux-badge/gux-badge.scss
  packages/genesys-spark-components/src/components/beta/gux-card/example.html
  packages/genesys-spark-components/src/components/beta/gux-card/gux-card.less
  packages/genesys-spark-components/src/components/beta/gux-card/gux-card.scss
  packages/genesys-spark-components/src/components/beta/gux-card/gux-card.tsx
  packages/genesys-spark-components/src/components/beta/gux-card/gux-card.types.ts
  packages/genesys-spark-components/src/components/beta/gux-card/readme.md
  packages/genesys-spark-components/src/components/beta/gux-card/tests/__snapshots__/gux-card.e2e.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-card/tests/__snapshots__/gux-card.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-card/tests/gux-card.e2e.ts
  packages/genesys-spark-components/src/components/beta/gux-card/tests/gux-card.spec.ts
  packages/genesys-spark-components/src/components/beta/gux-phone-input/readme.md
  packages/genesys-spark-components/src/components/beta/gux-tag/gux-tag.scss
  packages/genesys-spark-components/src/style/style.less
  packages/genesys-spark-tokens/.prettierignore
  packages/genesys-spark-tokens/data/tokens.json
  packages/genesys-spark-tokens/package.json
  packages/genesys-spark-tokens/snapshot/css/global.css
  packages/genesys-spark-tokens/snapshot/css/gse-core.css
  packages/genesys-spark-tokens/snapshot/css/gse-semantic.css
  packages/genesys-spark-tokens/snapshot/css/gse-ui.css
  packages/genesys-spark-tokens/snapshot/css/semantic.css
  packages/genesys-spark-tokens/snapshot/css/ui.css
  packages/genesys-spark-tokens/snapshot/json/global.json
  packages/genesys-spark-tokens/snapshot/json/gse-core.json
  packages/genesys-spark-tokens/snapshot/json/gse-semantic.json
  packages/genesys-spark-tokens/snapshot/json/gse-ui.json
  packages/genesys-spark-tokens/snapshot/json/ui.json
  packages/genesys-spark-tokens/snapshot/less/global.less
  packages/genesys-spark-tokens/snapshot/less/gse-core.less
  packages/genesys-spark-tokens/snapshot/less/gse-semantic.less
  packages/genesys-spark-tokens/snapshot/less/gse-ui.less
  packages/genesys-spark-tokens/snapshot/less/semantic.less
  packages/genesys-spark-tokens/snapshot/less/ui.less
  packages/genesys-spark-tokens/snapshot/scss/_global.scss
  packages/genesys-spark-tokens/snapshot/scss/_gse-core.scss
  packages/genesys-spark-tokens/snapshot/scss/_gse-semantic.scss
  packages/genesys-spark-tokens/snapshot/scss/_gse-ui.scss
  packages/genesys-spark-tokens/snapshot/scss/_semantic.scss
  packages/genesys-spark-tokens/snapshot/scss/_ui.scss
  packages/genesys-spark-tokens/utils/get-all-token-studio-files.mjs
  packages/genesys-spark-tokens/utils/output-styles.mjs
  packages/genesys-spark-tokens/utils/process-token-file.mjs
Labels: UX Input Needed, Spark Ember v2

#1328 fix(gux-popup-beta): hide popup when target element goes out of view
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.less
  packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.tsx
Labels: bug

#1374 chore(notification-toast): converting less files to scss
  package-lock.json
  packages/genesys-spark-components/src/components/stable/gux-notification-toast/gux-notification-toast.scss
  packages/genesys-spark-components/src/components/stable/gux-notification-toast/gux-notification-toast.tsx
  packages/genesys-spark-components/src/style/color-palette.scss
  packages/genesys-spark-components/src/style/color.scss
  packages/genesys-spark-components/src/style/focus.scss
  packages/genesys-spark-components/src/style/roboto.scss
  packages/genesys-spark-components/src/style/shadows.scss
  packages/genesys-spark-components/src/style/typography.scss
Labels: V4 Release Component Updates

#1394 refactor(inline-alert) - move from beta to stable
  packages/genesys-spark-components/documentation/migrations/v4/readme.md
  packages/genesys-spark-components/src/components/stable/gux-alert/example.html
  packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.less
  packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.tsx
  packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.types.ts
  packages/genesys-spark-components/src/components/stable/gux-alert/i18n/en.json
  packages/genesys-spark-components/src/components/stable/gux-alert/readme.md
  packages/genesys-spark-components/src/components/stable/gux-alert/tests/__snapshots__/gux-inline-alert.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-alert/tests/__snapshots__/gux-inline-alert.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-alert/tests/gux-inline-alert.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-alert/tests/gux-inline-alert.spec.ts
  packages/genesys-spark-components/src/components/stable/gux-icon/readme.md
  packages/genesys-spark-components/src/i18n/translations/en.json
Labels: V4 Release Component Updates

#1292 refactor(inline-alert) - component reskin
  packages/genesys-spark-components/src/components/stable/gux-alert/example.html
  packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.scss
  packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.tsx
  packages/genesys-spark-components/src/components/stable/gux-alert/readme.md
Labels: UX Approved, V4 Release Component Updates

#1409 refactor(truncate): move from beta to stable
  packages/genesys-spark-components/documentation/migrations/v4/readme.md
  packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/tests/__snapshots__/gux-dropdown-multi.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/readme.md
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/tests/__snapshots__/gux-pagination-items-per-page-beta.spec.ts.snap
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/readme.md
  packages/genesys-spark-components/src/components/beta/gux-phone-input/readme.md
  packages/genesys-spark-components/src/components/beta/gux-table/example.html
  packages/genesys-spark-components/src/components/beta/gux-truncate/tests/__snapshots__/gux-truncate.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-alert/example.html
  packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
  packages/genesys-spark-components/src/components/stable/gux-dropdown/readme.md
  packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/__snapshots__/gux-dropdown.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option/gux-option.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option/readme.md
  packages/genesys-spark-components/src/components/stable/gux-notification-toast/gux-notification-toast.tsx
  packages/genesys-spark-components/src/components/stable/gux-notification-toast/readme.md
  packages/genesys-spark-components/src/components/stable/gux-notification-toast/tests/__snapshots__/gux-notification-toast.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-pagination/readme.md
  packages/genesys-spark-components/src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-simple-toast/gux-simple-toast.tsx
  packages/genesys-spark-components/src/components/stable/gux-simple-toast/readme.md
  packages/genesys-spark-components/src/components/stable/gux-simple-toast/tests/__snapshots__/gux-simple-toast.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-tooltip/readme.md
  packages/genesys-spark-components/src/components/stable/gux-truncate/example.html
  packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.scss
  packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.tsx
  packages/genesys-spark-components/src/components/stable/gux-truncate/readme.md
  packages/genesys-spark-components/src/components/stable/gux-truncate/tests/__snapshots__/gux-truncate.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-truncate/tests/__snapshots__/gux-truncate.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-truncate/tests/gux-truncate.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-truncate/tests/gux-truncate.spec.ts
Labels: V4 Release Component Updates

#1402 Button Tokens
  packages/genesys-spark-components/src/components/beta/gux-button-slot/gux-button-slot.less
  packages/genesys-spark-components/src/components/beta/gux-button-slot/gux-button-slot.scss
  packages/genesys-spark-components/src/components/beta/gux-button-slot/gux-button-slot.tsx
  packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.less
  packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.scss
  packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx
  packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.less
  packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.scss
  packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx
  packages/genesys-spark-components/src/components/stable/gux-button/example.html
  packages/genesys-spark-components/src/components/stable/gux-button/gux-button.less
  packages/genesys-spark-components/src/components/stable/gux-button/gux-button.scss
  packages/genesys-spark-components/src/components/stable/gux-button/gux-button.tsx
Labels: V4 Release Component Updates

#1408 refactor(text-highlight): enabled shadow DOM
  packages/genesys-spark-components/src/components/beta/gux-phone-input/readme.md
  packages/genesys-spark-components/src/components/stable/gux-text-highlight/gux-text-highlight.scss
  packages/genesys-spark-components/src/components/stable/gux-text-highlight/gux-text-highlight.tsx
  packages/genesys-spark-components/src/components/stable/gux-text-highlight/tests/__snapshots__/gux-text-highlight.e2e.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-text-highlight/tests/__snapshots__/gux-text-hightlight.spec.ts.snap
  packages/genesys-spark-components/src/components/stable/gux-text-highlight/tests/gux-text-highlight.e2e.ts
Labels: V4 Release Component Updates

#1420 feat(listbox): made empty message configurable
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
  packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx
Labels: new api

#1421 refactor(page-loading-spinner): component now uses scss
  packages/genesys-spark-components/src/components/stable/gux-page-loading-spinner/gux-page-loading-spinner.scss
  packages/genesys-spark-components/src/components/stable/gux-page-loading-spinner/gux-page-loading-spinner.tsx
Labels: simple review, V4 Release Component Updates

#1422 refactor(tokens): updated tokens from UX
  packages/genesys-spark-tokens/data/tokens.json
  packages/genesys-spark-tokens/snapshot/css/gse-ui-feedback.css
  packages/genesys-spark-tokens/snapshot/css/gse-ui-formsAndInputs.css
  packages/genesys-spark-tokens/snapshot/json/gse-ui-feedback.json
  packages/genesys-spark-tokens/snapshot/json/gse-ui-formsAndInputs.json
  packages/genesys-spark-tokens/snapshot/less/gse-ui-feedback.less
  packages/genesys-spark-tokens/snapshot/less/gse-ui-formsAndInputs.less
  packages/genesys-spark-tokens/snapshot/scss/_gse-ui-feedback.scss
  packages/genesys-spark-tokens/snapshot/scss/_gse-ui-formsAndInputs.scss
Labels: simple review
