Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-03, with the labels that each got.

#1156 feat(table-toolbar): addition of disabled prop
  src/components/beta/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.tsx
  src/components/beta/gux-table-toolbar/gux-table-toolbar-action/readme.md
  src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/__snapshots__/gux-table-toolbar-action.e2e.ts.snap
  src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/__snapshots__/gux-table-toolbar-action.spec.ts.snap
  src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/gux-table-toolbar-action.e2e.ts
  src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/gux-table-toolbar-action.spec.ts
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/readme.md
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/__snapshots__/gux-table-toolbar-custom-action.e2e.ts.snap
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/__snapshots__/gux-table-toolbar-custom-action.spec.ts.snap
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/gux-table-toolbar-custom-action.e2e.ts
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/gux-table-toolbar-custom-action.spec.ts
Labels: simple review

#1172 fix(dropdown-multi): prevent text from overlapping
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
Labels: bug

#1170 feat(badge): allow custom colors
  src/components/beta/gux-badge/example.html
  src/components/beta/gux-badge/gux-badge.less
  src/components/beta/gux-badge/gux-badge.types.ts
  src/components/beta/gux-badge/i18n/en.json
  src/components/beta/gux-badge/readme.md
  src/components/beta/gux-badge/tests/__snapshots__/gux-badge.e2e.ts.snap
  src/components/beta/gux-badge/tests/__snapshots__/gux-badge.spec.ts.snap
  src/components/beta/gux-badge/tests/gux-badge.e2e.ts
  src/components/beta/gux-badge/tests/gux-badge.spec.ts
  src/i18n/translations/en.json
Labels: new api

#1199 fix(on-click-outside): addition of isConnected condition to if guard
  packages/genesys-spark-components/src/utils/decorator/on-click-outside.ts
Labels: bug

#1201 fix(component): using focus-visible throughout the app
  packages/genesys-spark-components/src/components/beta/gux-button-slot/gux-button-slot.less
  packages/genesys-spark-components/src/components/beta/gux-column-manager/gux-column-manager-item/gux-column-manager-item.less
  packages/genesys-spark-components/src/components/beta/gux-copy-to-clipboard/gux-copy-to-clipboard.less
  packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
  packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-calendar.less
  packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list-item/gux-month-list-item.less
  packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-picker.less
  packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.less
  packages/genesys-spark-components/src/components/beta/gux-table/gux-table-select-menu/gux-table-select-menu.less
  packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.less
  packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.tsx
  packages/genesys-spark-components/src/components/beta/gux-time-picker/tests/__snapshots__/gux-time-picker.spec.ts.snap
  packages/genesys-spark-components/src/components/legacy/gux-command-palette-legacy/gux-command-palette.less
  packages/genesys-spark-components/src/components/legacy/gux-dropdown-legacy/gux-dropdown.less
  packages/genesys-spark-components/src/components/legacy/gux-form-field-legacy/components/gux-input-checkbox/gux-input-checkbox.less
  packages/genesys-spark-components/src/components/legacy/gux-form-field-legacy/components/gux-input-color/components/gux-input-color-option/gux-input-color-option.less
  packages/genesys-spark-components/src/components/legacy/gux-form-field-legacy/components/gux-input-color/gux-input-color.less
  packages/genesys-spark-components/src/components/legacy/gux-form-field-legacy/components/gux-input-number/gux-input-number.less
  packages/genesys-spark-components/src/components/legacy/gux-form-field-legacy/components/gux-input-search/gux-input-search.less
  packages/genesys-spark-components/src/components/legacy/gux-form-field-legacy/components/gux-input-text-like/gux-input-text-like.less
  packages/genesys-spark-components/src/components/legacy/gux-list-legacy/list-item/gux-list-item.less
  packages/genesys-spark-components/src/components/legacy/gux-side-panel-legacy/buttons/gux-side-panel-button.less
  packages/genesys-spark-components/src/components/legacy/gux-tabs-legacy/gux-tab-dropdown-option-legacy/gux-tab-dropdown-option-legacy.less
  packages/genesys-spark-components/src/components/legacy/gux-tabs-legacy/gux-tab-legacy/gux-tab-legacy.less
  packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/gux-accordion-section.less
  packages/genesys-spark-components/src/components/stable/gux-advanced-dropdown/dropdown-option/gux-dropdown-option.less
  packages/genesys-spark-components/src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less
  packages/genesys-spark-components/src/components/stable/gux-button/gux-button.less
  packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.less
  packages/genesys-spark-components/src/components/stable/gux-content-search/gux-content-search.less
  packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.less
  packages/genesys-spark-components/src/components/stable/gux-dismiss-button/gux-dismiss-button.less
  packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.less
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.less
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.light.less
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.less
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.less
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.light.less
  packages/genesys-spark-components/src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.less
  packages/genesys-spark-components/src/components/stable/gux-list/gux-list-item/gux-list-item.less
  packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.less
  packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.less
  packages/genesys-spark-components/src/components/stable/gux-switch/gux-switch-item/gux-switch-item.less
  packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced-list/gux-tab-advanced-list.less
  packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.less
  packages/genesys-spark-components/src/style/examples/focus.html
  packages/genesys-spark-components/src/style/focus.less
  packages/genesys-spark-components/src/style/shared/text-input.less
  packages/genesys-spark-components/src/style/typography.less
Labels: ux review
