Repository MyPureCloud/genesys-webcomponents, pull requests merged in 2023-01, with the labels that each got.

#1064 fix(button-multi): align button and button-multi colours for disabled state.
  src/components/stable/gux-button-multi/gux-button-multi.tsx
Labels: bug, simple review

#1063 fix(tabs-advanced): fix issue where "enter" key does not open dropdown
  src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.tsx
Labels: bug, simple review

#1077 refactor(dropdown): change to behaviour of adding option to dropdown with unknown value set
  src/components/stable/gux-dropdown/gux-dropdown.tsx
Labels: simple review

#1074 refactor(tabs-advanced): add vertical separator, align text vertically
  src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.less
Labels: simple review

#1080 chore(dependencies): updated dependencies to wanted
  docs/package-lock.json
  docs/package.json
  package-lock.json
  package.json
  src/components/beta/gux-phone-input/readme.md
Labels: simple review

#1088 refactor(css): stopped using deprecated space less variables
  src/components/beta/gux-alert/gux-inline-alert.less
  src/components/beta/gux-badge/gux-badge.less
  src/components/beta/gux-blank-state/gux-blank-state.less
  src/components/beta/gux-button-slot/gux-button-slot.less
  src/components/beta/gux-card/gux-card.less
  src/components/beta/gux-copy-to-clipboard/gux-copy-to-clipboard.less
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi-tag/gux-dropdown-multi-tag.less
  src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
  src/components/beta/gux-loading-message/gux-loading-message.less
  src/components/beta/gux-month-picker/gux-month-calendar/gux-month-calendar.less
  src/components/beta/gux-month-picker/gux-month-picker.less
  src/components/beta/gux-pagination-beta/gux-pagination-beta.less
  src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/gux-pagination-buttons-beta.less
  src/components/beta/gux-pagination-beta/gux-pagination-item-counts-beta/gux-pagination-item-counts-beta.less
  src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/gux-pagination-items-per-page-beta.less
  src/components/beta/gux-phone-input/gux-phone-input.less
  src/components/beta/gux-popover-list/gux-popover-list.less
  src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.less
  src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.less
  src/components/beta/gux-table-toolbar/gux-table-toolbar.less
  src/components/beta/gux-table/gux-table-select-menu/gux-table-select-popover/gux-table-select-popover.less
  src/components/beta/gux-table/gux-table.light.less
  src/components/beta/gux-tag/gux-tag.less
  src/components/beta/gux-time-picker/gux-time-picker.less
  src/components/legacy/gux-accordion-legacy/gux-accordion.less
  src/components/legacy/gux-form-field-legacy/components/gux-input-range/gux-input-range.less
  src/components/legacy/gux-form-field-legacy/components/gux-input-search/gux-input-search.less
  src/components/legacy/gux-form-field-legacy/components/gux-input-text-like/gux-input-text-like.less
  src/components/stable/gux-accordion/gux-accordion-section/gux-accordion-section.less
  src/components/stable/gux-button-multi/gux-button-multi.less
  src/components/stable/gux-button-multi/gux-button-multi.light.less
  src/components/stable/gux-button/gux-button.less
  src/components/stable/gux-content-search/gux-content-search.less
  src/components/stable/gux-datepicker/gux-datepicker.less
  src/components/stable/gux-dismiss-button/gux-dismiss-button.less
  src/components/stable/gux-dropdown/gux-dropdown.less
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.less
  src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.light.less
  src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.less
  src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.less
  src/components/stable/gux-form-field/functional-components/gux-form-field-container/gux-form-field-container.less
  src/components/stable/gux-form-field/functional-components/gux-form-field-fieldset-container/gux-form-field-fieldset-container.less
  src/components/stable/gux-form-field/functional-components/gux-form-field-label/gux-form-field-label.less
  src/components/stable/gux-form-field/functional-components/gux-form-field-legend-label/gux-form-field-legend-label.less
  src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.less
  src/components/stable/gux-modal/gux-modal.less
  src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.less
  src/components/stable/gux-popover/gux-popover.less
  src/components/stable/gux-switch/gux-switch-item/gux-switch-item.less
  src/components/stable/gux-tabs-advanced/gux-tab-advanced-list/gux-tab-advanced-list.less
  src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.less
  src/components/stable/gux-tabs/gux-tab/gux-tab.less
  src/components/stable/gux-toggle/gux-toggle.less
  src/components/stable/gux-tooltip-title/gux-tooltip-title.less
  src/style/css-custom-properties.less
  src/style/spacing.less
  src/style/typography.less
Labels: simple review

#1094 feat(localisation): centralised en file is now getting localised by t…
  scripts/update-en-i18n.js
Labels: simple review

#1107 feat(gux-form-field-color): update design
  src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.less
Labels: ux review

#1116 fix(simple-toast): change icon size to 16x16
  src/components/stable/gux-simple-toast/gux-simple-toast.less
Labels: bug
